# Generated by Django 6.0.4 on 2026-05-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
